version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - network
    volumes:
      - postgresvol:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d/

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 5050:80

volumes:
  postgresvol:
    driver: local

networks:
  network:
    driver: bridge